#ifndef TOAD_H_CONFIG
#define TOAD_H_CONFIG
#include <iostream>
#include <string>
#include "allegro5/allegro.h"

int ts_load_config(char* path);

extern ALLEGRO_COLOR COLOR_MAIN_BG;
extern ALLEGRO_COLOR COLOR_MAIN_FONT;
extern ALLEGRO_COLOR COLOR_INPUT_BG;
extern ALLEGRO_COLOR COLOR_INPUT_BG_ACTIVE;
extern ALLEGRO_COLOR COLOR_INPUT_FONT;
extern ALLEGRO_COLOR COLOR_INPUT_BORDER;
extern ALLEGRO_COLOR COLOR_INPUT_BORDER_ACTIVE;
extern ALLEGRO_COLOR COLOR_BUTTON_BG;
extern ALLEGRO_COLOR COLOR_BUTTON_FONT;
extern ALLEGRO_COLOR COLOR_BUTTON_ALT_BG;
extern ALLEGRO_COLOR COLOR_BUTTON_ALT_FONT;
extern ALLEGRO_COLOR COLOR_VIEW_BG;
extern ALLEGRO_COLOR COLOR_VIEW_FONT;
extern ALLEGRO_COLOR COLOR_VIEW_ALT_BG;
extern ALLEGRO_COLOR COLOR_VIEW_ALT_FONT;

extern std::string CFG_TOOLTIP_ENABLE;
extern std::string CFG_TOOLTIP_TYPE;

extern int CFG_TOOLTIP_DELAY;
extern int CFG_TOOLTIP_SPROUT;
extern int CFG_TOOLTIP_WILT;


#endif // TOAD_H_CONFIG
